version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_R2DBC_URL=r2dbc:pool:mysql://localhost:3306/
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=root

  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"