version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cradle
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cradle
    ports:
      - "3300:3306"
